# Generated by Django 4.1.7 on 2023-05-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoffers',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartoffers',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='orderdiscounts',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderdiscounts',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdiscounts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdiscounts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderoffers',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderoffers',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderoffers',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderoffers',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='item',
            name='before_offer',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='instead_of',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='percentage',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carditems', to='store.item'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='spa',
            field=models.CharField(choices=[('قلب', 'قلب')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.DeleteModel(
            name='CartDiscounts',
        ),
        migrations.DeleteModel(
            name='CartOffers',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OrderDiscounts',
        ),
        migrations.DeleteModel(
            name='OrderOffers',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
